name: Weekly Merge and Commit Frequency Check

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  frequency-check:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-git@v2
        with:
          version: '2.x'  # You can specify the Git version you need

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with the version you need

      - name: Install SendGrid CLI
        run: npm install -g @sendgrid/mail

      - name: Calculate Merge and Commit Frequency
        run: |
          # Replace with your script to calculate merge and commit frequency
          # Example: Use Git to fetch data and calculate frequency
          git fetch
          merge_frequency=$(git log --oneline origin/master..origin/feature-branch | wc -l)
          commit_frequency=$(git log --oneline --since='1 week ago' | wc -l)
          echo "Merge Frequency: $merge_frequency" > frequency.txt
          echo "Commit Frequency (last week): $commit_frequency" >> frequency.txt
          
      - name: Send Email
        run: |
          # Replace with the code to send an email using SendGrid
          echo "Sending frequency data via email"
          sendgrid_mail="YOUR_SENDGRID_EMAIL"
          echo "Merge and Commit Frequency Report" | sendmail -t $sendgrid_mail < frequency.txt
